all done
marianamasia/project-group-15 pull request #13
Opened 2024-02-11 14:12 UTC by marianamasia

2024-02-11 20:28 UTC, andriiKrakovskyi requested changes

2024-02-11 20:28 UTC, andriiKrakovskyi commented on src/partials/footer.html
> +    <<<<<<< HEAD
удали HEAD - это кусок конфликта

2024-02-11 20:28 UTC, andriiKrakovskyi commented on src/partials/footer.html
> +  ======= >>>>>>> main
и это тоже от конфликта осталось

2024-02-12 10:19 UTC, marianamasia commented on src/partials/footer.html
> +    <<<<<<< HEAD
видалено

2024-02-12 10:19 UTC, marianamasia commented on src/partials/footer.html
> +  ======= >>>>>>> main
видалено

2024-02-12 10:31 UTC, andriiKrakovskyi approved these changes

2024-02-12 10:31 UTC, merged