Header section
marianamasia/project-group-15 pull request #9
Opened 2024-02-11 00:12 UTC by WiLexa

2024-02-11 10:56 UTC, andriiKrakovskyi requested changes

2024-02-11 10:56 UTC, andriiKrakovskyi commented on src/css/header.css
> +  padding-right: 20px;
хедер должен заходить на секцию hero

    position: absolute;
    top: 20px;
    left: 20px;
    right: 20px;
    z-index: 99999999999;

2024-02-11 10:56 UTC, andriiKrakovskyi commented on src/css/header.css
> +}
нельзя оставлять пустые классы

2024-02-12 17:53 UTC, marianamasia approved these changes

2024-02-12 17:54 UTC, marianamasia approved these changes

2024-02-12 17:55 UTC, marianamasia approved these changes

2024-02-12 19:39 UTC, andriiKrakovskyi approved these changes

2024-02-12 19:39 UTC, merged